# Generated by Django 4.1.5 on 2023-02-05 13:17

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("system_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("floor_count", models.IntegerField(default=0, null=True)),
                ("elevator_count", models.IntegerField(default=0, null=True)),
                ("bottommost_floor", models.IntegerField(null=True)),
                ("topmost_floor", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("current_floor_number", models.IntegerField()),
                ("destination_floor_number", models.IntegerField()),
                (
                    "elevator_assigned",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator.elevator",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator_admin.elevatorsystem",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
