# Generated by Django 4.1.5 on 2023-02-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elevator_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevatorsystem",
            name="bottommost_floor",
        ),
        migrations.RemoveField(
            model_name="elevatorsystem",
            name="topmost_floor",
        ),
    ]
