# Generated by Django 4.1.5 on 2023-02-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elevator_admin", "0005_elevatorrequest_is_resolved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevatorrequest",
            name="request_id",
        ),
        migrations.RemoveField(
            model_name="elevatorsystem",
            name="system_id",
        ),
    ]
