# Generated by Django 4.1.5 on 2023-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("elevator_id", models.UUIDField()),
            ],
        ),
    ]
