# Generated by Django 4.1.5 on 2023-01-30 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elevator", "0001_initial"),
        ("elevator_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="elevator_admin.elevatorsystem",
            ),
        ),
        migrations.AddField(
            model_name="elevator",
            name="system",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="elevator_admin.elevatorsystem",
            ),
        ),
    ]
