# Generated by Django 4.1.5 on 2023-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="door_status",
            field=models.CharField(
                choices=[("open", "Open"), ("close", "Close")],
                default="close",
                max_length=20,
            ),
        ),
    ]
