# Generated by Django 4.1.5 on 2023-02-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0003_elevator_door_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="direction",
            field=models.CharField(
                choices=[("up", "Up"), ("down", "Down"), ("idle", "Idle")],
                default="idle",
                max_length=20,
            ),
        ),
    ]
