# Generated by Django 4.1.5 on 2023-02-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0004_elevator_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevator",
            name="status",
            field=models.CharField(
                choices=[
                    ("busy", "Busy"),
                    ("available", "Available"),
                    ("Under Maintenance", "Under Maintenance"),
                ],
                default="available",
                max_length=50,
            ),
        ),
    ]
