name: GitHub Actions Workflow codebase push pipeline
run-name: ${{ github.actor }} triggered the push pipeline 🚀
on: 
  push:
    branches:
      - "*"
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r ${{ github.workspace }}/requirements-ci.txt
      - run: bash ${{ github.workspace }}/scripts/ci-lint.sh
        shell: bash

  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r ${{ github.workspace }}/requirements-ci.txt
      - name: Runs Unitests
        run: coverage run elevator_system/manage.py test elevator_system --settings=elevator_system.config.test
      - name: Coverage report
        run: |
          coverage report
          coverage html

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: pip install -r requirements.txt
      - name: Docker Login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build and Push 
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: ${{ github.ref }}
        run: |
          bash ${{ github.workspace }}/scripts/build-image.sh $DOCKER_USERNAME $IMAGE_NAME $IMAGE_TAG
      - name: Troubleshooting
        run: |
          echo "1. Make sure to have the Repository created in the dockerhub of SAME name as this repo."
          echo "2. Make sure to have the secrets stored with the above names"

