name: GitHub Actions Workflow codebase push pipeline
run-name: ${{ github.actor }} triggered the push pipeline 🚀
on: [push]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: pip install -r ${{ github.workspace }}/requirements-ci.txt
      - run: bash ${{ github.workspace }}/scripts/ci-lint.sh
        shell: bash

  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: pip install -r ${{ github.workspace }}/requirements-ci.txt
      - name: Runs Unitests 
        run: coverage run elevator_system/manage.py test --settings=elevator_system.config.test
      - name: Coverage report
        run: |
          coverage report
          coverage html
    needs:
      - linting

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: pip install -r ${{ github.workspace }}/requirements-ci.txt
      - run: echo "Build successful"
    needs:
      - unittests